//Set internal-use variables
A3XAI_unitLevels = [0,1,2,3];								
A3XAI_unitLevelsAll = A3XAI_unitLevels;				
A3XAI_curHeliPatrols = 0;									//Current number of active air patrols
A3XAI_curLandPatrols = 0;									//Current number of active land patrols
A3XAI_curUAVPatrols = 0;
A3XAI_curUGVPatrols = 0;
A3XAI_dynTriggerArray = [];									//List of all generated dynamic triggers.
A3XAI_staticTriggerArray = [];								//List of all static triggers
A3XAI_respawnQueue = [];									//Queue of AI groups that require respawning. Group ID is removed from queue after it is respawned.
A3XAI_areaBlacklists = [];									//Queue of temporary dynamic spawn area blacklists for deletion
A3XAI_checkedClassnames = [[],[],[]];						//Classnames verified - Weapons/Magazines/Vehicles
A3XAI_invalidClassnames = [[],[],[]];						//Classnames known as invalid - Weapons/Magazines/Vehicles
A3XAI_monitoredObjects = []; //used to cleanup AI vehicles that may not be destroyed.
A3XAI_activeGroups = [];
A3XAI_locations = [];
A3XAI_locationsAir = [];
A3XAI_locationsLand = [];
A3XAI_heliTypesUsable = [];
A3XAI_vehTypesUsable = [];
A3XAI_UAVTypesUsable = [];
A3XAI_UGVTypesUsable = [];
A3XAI_randTriggerArray = [];
A3XAI_mapMarkerArray = [];
A3XAI_weaponTypeIndices0 = [];
A3XAI_weaponTypeIndices1 = [];
A3XAI_weaponTypeIndices2 = [];
A3XAI_weaponTypeIndices3 = [];
A3XAI_failedDynamicSpawns = [];
A3XAI_HCObject = objNull;
A3XAI_HCIsConnected = false;
A3XAI_HCObjectOwnerID = 0;
A3XAI_activeGroupAmount = 0;
A3XAI_staticInfantrySpawnQueue = [];
A3XAI_customBlacklistQueue = [];
A3XAI_customInfantrySpawnQueue = [];
A3XAI_createCustomSpawnQueue = [];
A3XAI_customVehicleSpawnQueue = [];
A3XAI_randomInfantrySpawnQueue = [];
A3XAI_activeReinforcements = [];
A3XAI_reinforcedPositions = [];
A3XAI_spawnChanceMultiplier = 1;
A3XAI_HCAllowedTypes = ["static", "dynamic", "random", "air", "land", "staticcustom", "aircustom", "landcustom", "vehiclecrew", "air_reinforce", "uav", "ugv"];
A3XAI_lastGroupTransfer = 0;
A3XAI_automatedUnitTypes = ["uav","ugv"];
A3XAI_noAggroAreas = [];
